import { Vec2 } from "./Vec2";
import { Vec3 } from "./Vec3";
import { Vec4 } from "./Vec4";
import { VecN } from "./VecN";
import { Matrix4 } from "../Matrix4";
export declare function vec2(x: number, y: number): Vec2;
export declare function vec2(x: number): Vec2;
export declare function vec2(v: Vec2 | Vec3 | Vec4 | VecN): Vec2;
export declare function vec2(): Vec2;
export declare function vec3(x: number, y: number, z: number): Vec3;
export declare function vec3(x: number, y: number): Vec3;
export declare function vec3(x: number): Vec3;
export declare function vec3(v: Vec3 | Vec4 | VecN): Vec3;
export declare function vec3(): Vec3;
export declare function vec4(x: number, y: number, z: number, w: number): Vec4;
export declare function vec4(x: number, y: number, z: number): Vec4;
export declare function vec4(x: number, y: number): Vec4;
export declare function vec4(v: Vec3, w: number): Vec4;
export declare function vec4(x: number): Vec4;
export declare function vec4(v: Vec2 | Vec3 | VecN): Vec4;
export declare function vec4(): Vec4;
export declare const vecn: (...values: number[]) => VecN;
export declare function vec(x: number): VecN;
export declare function vec(x: number, y: number): Vec2;
export declare function vec(x: number, y: number, z: number): Vec3;
export declare function vec(x: number, y: number, z: number, w: number): Vec4;
export declare function vec(...values: number[]): VecN;
export declare function mat4(s: number): Matrix4;
export declare function mat4(coeffs: Float32Array): Matrix4;
export declare function mat4(...coeffs: number[]): Matrix4;
export declare function mat4(row_1: Vec4, row_2: Vec4, row_3: Vec4, row_4: Vec4): Matrix4;
